nelmio_api_doc:
    documentation:
        info:
            title: My Diplom - food blog web-application
            description: This is an API documentation for food blog application!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
