version: '3.3'

services:
  nginx:
    container_name: diplom_nginx
    build:
      context: docker/nginx
    volumes:
      - .:/diplom
    restart: always
    depends_on:
      - php-fpm
    ports:
      - "88:88"
    networks:
      - diplom

  php-fpm:
    container_name: diplom_php_fpm
    build:
      context: docker/php-fpm
    volumes:
      - .:/diplom
    depends_on:
      - mysql
    networks:
      - diplom

  php-cli:
    container_name: diplom_php_cli
    build:
      context: docker/php-cli
    volumes:
      - .:/diplom
    depends_on:
      - mysql
    networks:
      - diplom

  mysql:
    container_name: diplom_mysql
    image: library/mysql:8.0
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: always
    env_file:
      - .env
    environment:
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    ports:
      - "3306:3306"
    networks:
      - diplom

  minio:
    container_name: diplom_minio
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio:/data
    env_file:
      - .env
    environment:
      - "MINIO_ROOT_USER=${AWS_KEY}"
      - "MINIO_ROOT_PASSWORD=${AWS_SECRET}"
    command: server /data --console-address ":9001"
    networks:
      - diplom

networks:
  diplom:
